### ISSUE TITLE
error when trying to create a store

### ISSUE THREAD

**Issue by neverender** [creationix/nstore#15]
node v0.3.3
nstore v0.3.0

node.js:68
      throw e; // process.nextTick error, or 'error' event on first tick
      ^
TypeError: Object #<an initialize> has no method 'loadDatabase'
    at new initialize (/usr/local/lib/node/.npm/nstore/0.3.0/package/lib/nstore.js:28:10)
    at Object.anonymous (eval at extend (/usr/local/lib/node/.npm/pattern/0.1.0/package/lib/pattern.js:24:56))
    at Object.<anonymous> (/home/nick/dev/pad/device/http.js:7:22)
    at Module._compile (node.js:360:32)
    at Object..js (node.js:368:14)
    at Module.load (node.js:291:27)
    at Array.<anonymous> (node.js:382:26)
    at EventEmitter._tickCallback (node.js:60:24)

**Comment by creationix** [comment]
Fixed now, was a bug in the pattern library.
