### ISSUE TITLE
loadDatabase fails with an error in Buffer module "targetStart out of bounds"

### ISSUE THREAD

**Issue by milani** [creationix/nstore#21]
Loading Database into buffers when it is a little bigger than 2.0 KB is buggy. here is stack trace:

Error: targetStart out of bounds
    at Buffer.copy (buffer.js:366:11)
    at loadDatabase (/usr/local/lib/node/.npm/nStore/0.2.1/package/lib/nstore.js:202:13)
    at nStore (/usr/local/lib/node/.npm/nStore/0.2.1/package/lib/nstore.js:243:3)

I think shifting the input back down as you commented in nstore.js cause this bug.

**Comment by creationix** [comment]
Try again, seems to be working now.
